package com.finmind.premium;

public enum AdditionalOption {
    LIVING_BENEFIT,
    ACCIDENTAL_DEATH_RIDER,
    CHRONICLE_ILLNESS_RIDER,
    CRITICAL_ILLNESS_RIDER,
    TERMINAL_ILLNESS_RIDER,
    CHILDREN_RIDER,
}
